layout_spectrum: 0.3276596
favicon: null
name: TINIKI
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.5625
  lightness: 0.6659575
  saturation: 0.6680851
  rhythmicContrast: 0.4510638
  brandColors:
    - '#114278'
    - '#70a3c4'
    - '#8a7860'
    - '#e9b2b5'
    - '#00010d'
typography_spectrum: 0.4106383
