name: TINIKI
favicon: null
layout_spectrum: 0.26803
typography_spectrum: 0.4272260731086135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#114278'
    - '#70a3c4'
    - '#8a7860'
    - '#e9b2b5'
    - '#00010d'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
