name: TINIKI
favicon: null
layout_spectrum: 0.4122
typography_spectrum: 0.4272260731086135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#114278'
    - '#70a3c4'
    - '#8a7860'
    - '#e9b2b5'
    - '#00010d'
  brandStrength: 0.5828129420988262
  lightness: 0.7961624949239194
  saturation: 0.3546532781329006
  rhythmicContrast: 0.75
purpose: []
