name: TINIKI
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4272260731086135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5828129420988262
  lightness: 0.7961624949239194
  saturation: 0.3546532781329006
  rhythmicContrast: 0.75
purpose: []
